FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/user_service /app

ENV DATABASE_URL = ${DATABASE_URL}

RUN pip install pytest

CMD ["pytest"]