# 베이스 이미지 설정
FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# 종속성 파일 복사
COPY requirements.txt .

# 종속성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# 데이터베이스 URL 환경 변수 설정
ENV DATABASE_URL = ${DATABASE_URL}

# pytest 설치 (테스트 실행을 위해 필요)
RUN pip install pytest

# 테스트 실행
CMD ["pytest"]