"""duration to level

Revision ID: 409ccb886a65
Revises: 51f2ea1cc234
Create Date: 2024-07-18 13:17:39.955479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409ccb886a65'
down_revision: Union[str, None] = '51f2ea1cc234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_level_mapping',
    sa.Column('workout_level', sa.Integer(), nullable=False),
    sa.Column('workout_level_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('workout_level')
    )
    op.create_index(op.f('ix_workout_level_mapping_workout_level'), 'workout_level_mapping', ['workout_level'], unique=False)
    op.create_index(op.f('ix_workout_level_mapping_workout_level_name'), 'workout_level_mapping', ['workout_level_name'], unique=False)
    op.drop_index('ix_workout_duration_mapping_workout_duration', table_name='workout_duration_mapping')
    op.drop_index('ix_workout_duration_mapping_workout_duration_name', table_name='workout_duration_mapping')
    op.drop_table('workout_duration_mapping')
    op.add_column('members', sa.Column('workout_level', sa.Integer(), nullable=True))
    op.drop_column('members', 'workout_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('workout_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('members', 'workout_level')
    op.create_table('workout_duration_mapping',
    sa.Column('workout_duration', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_duration_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workout_duration', name='workout_duration_mapping_pkey')
    )
    op.create_index('ix_workout_duration_mapping_workout_duration_name', 'workout_duration_mapping', ['workout_duration_name'], unique=False)
    op.create_index('ix_workout_duration_mapping_workout_duration', 'workout_duration_mapping', ['workout_duration'], unique=False)
    op.drop_index(op.f('ix_workout_level_mapping_workout_level_name'), table_name='workout_level_mapping')
    op.drop_index(op.f('ix_workout_level_mapping_workout_level'), table_name='workout_level_mapping')
    op.drop_table('workout_level_mapping')
    # ### end Alembic commands ###
