"""added session count

Revision ID: 60cbb0d78c0a
Revises: 409ccb886a65
Create Date: 2024-07-18 16:11:00.504849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cbb0d78c0a'
down_revision: Union[str, None] = '409ccb886a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_member_mapping', sa.Column('remaining_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_member_mapping', 'remaining_sessions')
    # ### end Alembic commands ###
