"""“firebase


Revision ID: 68ee1356f01d
Revises: 
Create Date: 2024-07-25 12:11:24.329228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ee1356f01d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('workout_level', sa.Integer(), nullable=True),
    sa.Column('workout_frequency', sa.Integer(), nullable=True),
    sa.Column('workout_goal', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('member', 'trainer', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_uid'), 'members', ['uid'], unique=False)
    op.create_table('trainers',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('member', 'trainer', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_trainers_email'), 'trainers', ['email'], unique=True)
    op.create_index(op.f('ix_trainers_uid'), 'trainers', ['uid'], unique=False)
    op.create_table('workout_frequency_mapping',
    sa.Column('workout_frequency', sa.Integer(), nullable=False),
    sa.Column('workout_frequency_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('workout_frequency')
    )
    op.create_index(op.f('ix_workout_frequency_mapping_workout_frequency'), 'workout_frequency_mapping', ['workout_frequency'], unique=False)
    op.create_index(op.f('ix_workout_frequency_mapping_workout_frequency_name'), 'workout_frequency_mapping', ['workout_frequency_name'], unique=False)
    op.create_table('workout_goal_mapping',
    sa.Column('workout_goal', sa.Integer(), nullable=False),
    sa.Column('workout_goal_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('workout_goal')
    )
    op.create_index(op.f('ix_workout_goal_mapping_workout_goal'), 'workout_goal_mapping', ['workout_goal'], unique=False)
    op.create_index(op.f('ix_workout_goal_mapping_workout_goal_name'), 'workout_goal_mapping', ['workout_goal_name'], unique=False)
    op.create_table('workout_level_mapping',
    sa.Column('workout_level', sa.Integer(), nullable=False),
    sa.Column('workout_level_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('workout_level')
    )
    op.create_index(op.f('ix_workout_level_mapping_workout_level'), 'workout_level_mapping', ['workout_level'], unique=False)
    op.create_index(op.f('ix_workout_level_mapping_workout_level_name'), 'workout_level_mapping', ['workout_level_name'], unique=False)
    op.create_table('trainer_member_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_uid', sa.String(), nullable=True),
    sa.Column('member_uid', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', name='mappingstatus'), nullable=True),
    sa.Column('requester_uid', sa.String(), nullable=True),
    sa.Column('remaining_sessions', sa.Integer(), nullable=True),
    sa.Column('acceptance_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_uid'], ['members.uid'], ),
    sa.ForeignKeyConstraint(['trainer_uid'], ['trainers.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_member_mapping_id'), 'trainer_member_mapping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_member_mapping_id'), table_name='trainer_member_mapping')
    op.drop_table('trainer_member_mapping')
    op.drop_index(op.f('ix_workout_level_mapping_workout_level_name'), table_name='workout_level_mapping')
    op.drop_index(op.f('ix_workout_level_mapping_workout_level'), table_name='workout_level_mapping')
    op.drop_table('workout_level_mapping')
    op.drop_index(op.f('ix_workout_goal_mapping_workout_goal_name'), table_name='workout_goal_mapping')
    op.drop_index(op.f('ix_workout_goal_mapping_workout_goal'), table_name='workout_goal_mapping')
    op.drop_table('workout_goal_mapping')
    op.drop_index(op.f('ix_workout_frequency_mapping_workout_frequency_name'), table_name='workout_frequency_mapping')
    op.drop_index(op.f('ix_workout_frequency_mapping_workout_frequency'), table_name='workout_frequency_mapping')
    op.drop_table('workout_frequency_mapping')
    op.drop_index(op.f('ix_trainers_uid'), table_name='trainers')
    op.drop_index(op.f('ix_trainers_email'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_members_uid'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
