"""accepted date

Revision ID: 797e49ef7a31
Revises: e6d9fe7d129f
Create Date: 2024-07-22 14:42:37.107480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797e49ef7a31'
down_revision: Union[str, None] = 'e6d9fe7d129f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_member_mapping', sa.Column('acceptance_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_member_mapping', 'acceptance_date')
    # ### end Alembic commands ###
