"""requestor id

Revision ID: 9008375b213b
Revises: 8ab74d2d8558
Create Date: 2024-07-09 13:34:35.232304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9008375b213b'
down_revision: Union[str, None] = '8ab74d2d8558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_user_mapping', sa.Column('requester_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_user_mapping', 'requester_id')
    # ### end Alembic commands ###
