"""user to member

Revision ID: 01a41f231799
Revises: aca2d64e0d88
Create Date: 2024-07-16 17:43:35.934153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a41f231799'
down_revision: Union[str, None] = 'aca2d64e0d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('workout_duration', sa.Integer(), nullable=True),
    sa.Column('workout_frequency', sa.Integer(), nullable=True),
    sa.Column('workout_goal', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('member', 'trainer', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=True)
    op.create_table('trainer_member_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.String(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', name='mappingstatus'), nullable=True),
    sa.Column('requester_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_member_mapping_id'), 'trainer_member_mapping', ['id'], unique=False)
    op.drop_index('ix_trainer_user_mapping_id', table_name='trainer_user_mapping')
    op.drop_table('trainer_user_mapping')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('workout_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workout_frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workout_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('user', 'trainer', name='userrole'), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('trainer_user_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', name='mappingstatus'), autoincrement=False, nullable=True),
    sa.Column('requester_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], name='trainer_user_mapping_trainer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='trainer_user_mapping_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trainer_user_mapping_pkey')
    )
    op.create_index('ix_trainer_user_mapping_id', 'trainer_user_mapping', ['id'], unique=False)
    op.drop_index(op.f('ix_trainer_member_mapping_id'), table_name='trainer_member_mapping')
    op.drop_table('trainer_member_mapping')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
