"""modifying user_trainer map database

Revision ID: a2ef9688e04e
Revises: dc55ed0449b1
Create Date: 2024-07-09 11:28:33.235036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ef9688e04e'
down_revision: Union[str, None] = 'dc55ed0449b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_user_mapping', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='mappingstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_user_mapping', 'status')
    # ### end Alembic commands ###
