# Python 3.12 이미지 사용
FROM python:3.12-alpine 

# 작업 디렉토리 설정
WORKDIR /app

# requirements.txt 파일 복사 및 패키지 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# 현재 디렉토리 내용물 컨테이너에 복사
COPY . .

# 실행 명령어 설정
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8040"]