"""quest post models

Revision ID: 2867a84d7a40
Revises: dc5068345d81
Create Date: 2024-07-16 09:27:05.698882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2867a84d7a40'
down_revision: Union[str, None] = 'dc5068345d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('quest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('quest_id')
    )
    op.create_table('quest_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('workout_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.quest_id'], ),
    sa.ForeignKeyConstraint(['workout_key'], ['workout_key_name_map.workout_key_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_exercise_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rest_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['quest_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_exercise_sets')
    op.drop_table('quest_exercises')
    op.drop_table('quests')
    # ### end Alembic commands ###
