"""exercise to workout name changed

Revision ID: 4994cabfebe2
Revises: 2e92c461ef9c
Create Date: 2024-07-16 14:05:35.975897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4994cabfebe2'
down_revision: Union[str, None] = '2e92c461ef9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_workouts',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('workout_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.quest_id'], ),
    sa.ForeignKeyConstraint(['workout_key'], ['workout_key_name_map.workout_key_id'], ),
    sa.PrimaryKeyConstraint('quest_id', 'workout_key'),
    sa.UniqueConstraint('quest_id', 'workout_key', name='uq_quest_workout')
    )
    op.create_table('quest_workout_sets',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('workout_key', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rest_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id', 'workout_key'], ['quest_workouts.quest_id', 'quest_workouts.workout_key'], name='fk_quest_workout_set_workout'),
    sa.PrimaryKeyConstraint('quest_id', 'workout_key', 'set_number')
    )
    op.drop_table('quest_exercise_sets')
    op.drop_table('quest_exercises')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_exercises',
    sa.Column('quest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.quest_id'], name='quest_exercises_quest_id_fkey'),
    sa.ForeignKeyConstraint(['workout_key'], ['workout_key_name_map.workout_key_id'], name='quest_exercises_workout_key_fkey'),
    sa.UniqueConstraint('quest_id', 'workout_key', name='uq_quest_exercise'),
    postgresql_ignore_search_path=False
    )
    op.create_table('quest_exercise_sets',
    sa.Column('set_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quest_id', 'workout_key'], ['quest_exercises.quest_id', 'quest_exercises.workout_key'], name='fk_quest_exercise_set_exercise')
    )
    op.drop_table('quest_workout_sets')
    op.drop_table('quest_workouts')
    # ### end Alembic commands ###
