"""session id map added session type

Revision ID: 7da87fa49dd1
Revises: 8ed809ffd50a
Create Date: 2024-07-15 17:46:51.220515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da87fa49dd1'
down_revision: Union[str, None] = '8ed809ffd50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_part_id_name_map',
    sa.Column('workout_part_id', sa.Integer(), nullable=False),
    sa.Column('workout_part_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('workout_part_id')
    )
    op.add_column('workout_key_name_mapping', sa.Column('workout_part_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workout_key_name_mapping', 'workout_part_id_name_map', ['workout_part_id'], ['workout_part_id'])
    op.drop_column('workout_key_name_mapping', 'workout_part')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_key_name_mapping', sa.Column('workout_part', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_key_name_mapping', type_='foreignkey')
    op.drop_column('workout_key_name_mapping', 'workout_part_id')
    op.drop_table('workout_part_id_name_map')
    # ### end Alembic commands ###
