"""session id map added session type

Revision ID: ad9a92694e88
Revises: 242d06604265
Create Date: 2024-07-15 17:37:47.462789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9a92694e88'
down_revision: Union[str, None] = '242d06604265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_id_mapping', sa.Column('session_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_id_mapping', 'session_type_map', ['session_type_id'], ['session_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_id_mapping', type_='foreignkey')
    op.drop_column('session_id_mapping', 'session_type_id')
    # ### end Alembic commands ###
