"""workouts met and sec per rep

Revision ID: c73ae6ab574f
Revises: 7ebcbe63221b
Create Date: 2024-07-22 15:09:01.516566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73ae6ab574f'
down_revision: Union[str, None] = '7ebcbe63221b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('low_met', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('mid_met', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('high_met', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('sec_per_rep', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'sec_per_rep')
    op.drop_column('workouts', 'high_met')
    op.drop_column('workouts', 'mid_met')
    op.drop_column('workouts', 'low_met')
    # ### end Alembic commands ###
