"""workout model change

Revision ID: 03881d0e46b0
Revises: 3e41a9ceb7ee
Create Date: 2024-07-15 11:30:56.097009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03881d0e46b0'
down_revision: Union[str, None] = '3e41a9ceb7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_type_map', sa.Column('session_type', sa.String(), nullable=False))
    op.drop_column('session_type_map', 'sesison_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_type_map', sa.Column('sesison_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('session_type_map', 'session_type')
    # ### end Alembic commands ###
