"""id integer to str

Revision ID: 242d06604265
Revises: 03881d0e46b0
Create Date: 2024-07-15 16:58:57.614996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d06604265'
down_revision: Union[str, None] = '03881d0e46b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('reps', sa.Integer(), nullable=False))
    op.add_column('session', sa.Column('rest_time', sa.Integer(), nullable=False))
    op.alter_column('session_id_mapping', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('session_id_mapping', 'trainer_uid',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_id_mapping', 'trainer_uid',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('session_id_mapping', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('session', 'rest_time')
    op.drop_column('session', 'reps')
    # ### end Alembic commands ###
