"""workout model change

Revision ID: 3e41a9ceb7ee
Revises: 85eb8dfa2b93
Create Date: 2024-07-15 11:26:12.925639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e41a9ceb7ee'
down_revision: Union[str, None] = '85eb8dfa2b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_type_map',
    sa.Column('session_type_id', sa.Integer(), nullable=False),
    sa.Column('sesison_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('session_type_id')
    )
    op.create_index(op.f('ix_session_type_map_session_type_id'), 'session_type_map', ['session_type_id'], unique=False)
    op.add_column('session_id_mapping', sa.Column('session_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_id_mapping', 'session_type_map', ['session_type'], ['session_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_id_mapping', type_='foreignkey')
    op.drop_column('session_id_mapping', 'session_type')
    op.drop_index(op.f('ix_session_type_map_session_type_id'), table_name='session_type_map')
    op.drop_table('session_type_map')
    # ### end Alembic commands ###
