"""trainer id nullable

Revision ID: 85eb8dfa2b93
Revises: 0ff236b1bdf8
Create Date: 2024-07-10 10:48:15.512499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85eb8dfa2b93'
down_revision: Union[str, None] = '0ff236b1bdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_user_mapping')
    op.drop_index('ix_trainers_email', table_name='trainers')
    op.drop_index('ix_trainers_trainer_id', table_name='trainers')
    op.drop_table('trainers')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    op.alter_column('session_id_mapping', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_id_mapping', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('trainers',
    sa.Column('trainer_id', sa.INTEGER(), server_default=sa.text("nextval('trainers_trainer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trainer_id', name='trainers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_trainers_trainer_id', 'trainers', ['trainer_id'], unique=True)
    op.create_index('ix_trainers_email', 'trainers', ['email'], unique=True)
    op.create_table('trainer_user_mapping',
    sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], name='trainer_user_mapping_trainer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='trainer_user_mapping_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_id', 'user_id', name='trainer_user_mapping_pkey')
    )
    # ### end Alembic commands ###
