"""session id map added session type

Revision ID: 8ed809ffd50a
Revises: ad9a92694e88
Create Date: 2024-07-15 17:42:18.479159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed809ffd50a'
down_revision: Union[str, None] = 'ad9a92694e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_id_mapping_session_type_fkey', 'session_id_mapping', type_='foreignkey')
    op.drop_column('session_id_mapping', 'session_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_id_mapping', sa.Column('session_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('session_id_mapping_session_type_fkey', 'session_id_mapping', 'session_type_map', ['session_type'], ['session_type_id'])
    # ### end Alembic commands ###
