"""user to member

Revision ID: de4925251f0a
Revises: 4994cabfebe2
Create Date: 2024-07-16 17:48:19.375687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4925251f0a'
down_revision: Union[str, None] = '4994cabfebe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_quest_workout', 'quest_workouts', ['quest_id', 'workout_key'])
    op.add_column('quests', sa.Column('member_uid', sa.String(), nullable=False))
    op.drop_column('quests', 'user_id')
    op.add_column('session_id_mapping', sa.Column('member_uid', sa.String(), nullable=False))
    op.drop_column('session_id_mapping', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_id_mapping', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('session_id_mapping', 'member_uid')
    op.add_column('quests', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('quests', 'member_uid')
    op.drop_constraint('uq_quest_workout', 'quest_workouts', type_='unique')
    # ### end Alembic commands ###
